import { library } from '@fortawesome/fontawesome-svg-core';
import { fab } from '@fortawesome/free-brands-svg-icons';
import {
  faBolt,
  faBars,
  faTimes,
  faCheckCircle,
  faCheck,
  faMoneyBillWave,
  faChartLine,
  faBullhorn,
  faBullseye,
  faChartBar,
  faRocket,
  faUsers,
  faSearch,
  faGraduationCap,
  faLightbulb,
  faMap,
  faCode,
  faEnvelope,
  faPhone,
  faMapMarkerAlt,
  faCalendarCheck,
  faLock,
  faQuoteLeft,
  faArrowRight,
  faFileInvoiceDollar,
  faPlus
} from '@fortawesome/free-solid-svg-icons';

// Add all icons to the library so we can use them without importing them individually
library.add(
  fab,
  faBolt,
  faBars,
  faTimes,
  faCheckCircle,
  faCheck,
  faMoneyBillWave,
  faChartLine,
  faBullhorn,
  faBullseye,
  faChartBar,
  faRocket,
  faUsers,
  faSearch,
  faGraduationCap,
  faLightbulb,
  faMap,
  faCode,
  faEnvelope,
  faPhone,
  faMapMarkerAlt,
  faCalendarCheck,
  faLock,
  faQuoteLeft,
  faArrowRight,
  faFileInvoiceDollar,
  faPlus
);